### ISSUE TITLE
Issue Templates Comment Mistakes

### ISSUE THREAD

**Issue by euhidaman** [PUGroups/Support#46]
**Describe the bug**
There is a small problem, present in the comments of the **Joining Organization Issue template** and  the **Bug report Issue template**.
The comment states **'Where did you meet Eddie?'** (in the **Joining Organization Issue template** ), and,
in the bug report it states **'Feel free to check out other cool repositories of EddieHub Community'**, indicating clearly that this repository has been forked from EddieHub.
So, to remove confusion and to let new joiners contribute properly, please fix this mistake.  

**To Reproduce**
1. Go to https://github.com/PUGroups/Support/issues
2. Click on 'New Issue'
3. Create any issue, such as **Invitation to the GitHub Community Organization** or **Bug report**
4. See error as shown on the screenshots

**Expected behavior**
Rather Than EdiieHub, it should be PUGroups in the comments.

**Screenshots -->**
*Joining Organization Issue template : *
![Screenshot_5](https://user-images.githubusercontent.com/65843257/129132518-24e44a58-3d6d-4f63-a375-db380425aa31.jpg)

*Bug report Issue template : *
![Screenshot_6](https://user-images.githubusercontent.com/65843257/129132634-3af85834-0706-45b6-a7f3-c33bf640641e.jpg)

**Comment by PulkitSinghDev** [comment]
thanks for sharing these things with us, we have resolved it now 😄
