### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by phanatagama** [PUGroups/Support#71]
Your name
Cahyadi Setia Phanatagama

Discord username (if exists)
nothing

Additional context
When I was exploring GitHub I came across the profile of Pulkit

**Comment by Panquesito7** [comment]
Hey, @phanatagama. We have an issue template for that. The bot will automatically invite you to the GitHub organization. Click [here](https://github.com/PUGroups/support/issues/new/choose) and choose the option below.

![image](https://user-images.githubusercontent.com/51391473/135141170-d68a7bb5-ddb8-42ec-bd01-354fb89f5062.png)
